gtd/tracker/urls.py
from django.conf.urls import url

from .views import Dashboard, TaskDetails, ProjectDetails

app_name = 'gtd'

urlpatterns = [
    url(r'dashboard/$', Dashboard.as_view(), name='dashboard'),
    url(r'project/(?P<pk>[0-9]+)/$', ProjectDetails.as_view(), name='project-details'),
    url(r'task/(?P<pk>[0-9]+)/$', TaskDetails.as_view(), name='task-details'),

]

gtd/urls.py
from django.contrib import admin
from django.urls import path



admin.site.site_header = "Kolejny tracker zadań"
admin.site.site_title = "Kolejny tracker zadań"
admin.site.index_title = "Witaj w kolejnym trackerze zadań - GTD"


urlpatterns = [
    path('haha/', admin.site.urls),
]

gtd/config/models.py
from django.db import models
from solo.models import SingletonModel


class SiteConfiguration(SingletonModel):
    site_name = models.CharField(max_length=255, default='Site Name')
    maintenance_mode = models.BooleanField(default=False)

    def __str__(self):
        return "Site Configuration"

    class Meta:
        verbose_name = "Site Configuration"

gtd/tags/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(
        max_length=255
    )

    added_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

gtd/tracker/models.py
from django.contrib.auth.models import User
from django.db import models

from simple_history.models import HistoricalRecords

from gtd.tags.models import Tag


class ProjectCategory(models.Model):
    parent = models.ForeignKey(
        'self',
        blank=True,
        null=True,
        on_delete=models.PROTECT)
    name = models.CharField(
        max_length=255
    )
    path = models.CharField(
        max_length=255,
        blank=True
    )

    added_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Project categories'

    def __str__(self):
        if self.parent:
            return '- {}'.format(self.name)
        else:
            return self.name

    def subcategories(self):
        return ProjectCategory.objects.filter(parent=self).order_by('name')

    def save(self, *args, **kwargs):
        if self.parent:
            self.path = '{} > {}'.format(self.parent.name, self.name)
        else:
            self.path = self.name
        return super(ProjectCategory, self).save(*args, **kwargs)


class Project(models.Model):
    categories = models.ManyToManyField(
        ProjectCategory,
        blank=True,
        related_name='projects'
    )
    name = models.CharField(
        max_length=255
    )
    description = models.TextField(
        blank=True,
        null=True,
        help_text='Tutaj wpisz ogólny opis projektu - misję, założenia, ograniczenia itd itd.'
    )
    tags = models.ManyToManyField(
        Tag,
        blank=True,
    )

    added_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)

    history = HistoricalRecords()

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return self.name

    def tasks(self):
        return Task.objects.filter(projects=self)


class Task(models.Model):
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    NEW = 'new'
    PENDING = 'pending'
    CANCELLED = 'cancelled'
    DONE = 'done'
    STATUS_CHOICES = (
        (NEW, 'nowe'),
        (PENDING, 'w trakcie'),
        (CANCELLED, 'anulowane'),
        (DONE, 'zrobione')
    )
    status = models.CharField(
        max_length=100,
        choices=STATUS_CHOICES,
        default=NEW
    )
    name = models.CharField(
        max_length=255
    )
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, blank=True, null=True,
    )
    link = models.URLField(
        blank=True,
        null=True
    )
    description = models.TextField(
        blank=True,
        null=True
    )
    priority = models.IntegerField(
        default=100
    )
    tags = models.ManyToManyField(
        Tag,
        blank=True,
    )

    added_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)

    history = HistoricalRecords()

    def __str__(self):
        return self.name

gtd/tracker/forms.py
from django import forms

from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('categories', 'name', 'description', 'tags')

gtd/tags/views.py
from django.shortcuts import render

# Create your views here.

gtd/tracker/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView, CreateView

from .forms import ProjectForm
from .models import *


class Dashboard(TemplateView):
    template_name = 'gtd/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        context['categories'] = ProjectCategory.objects.filter(parent=None)
        context['add_project_form'] = ProjectForm()
        return context


class TaskDetails(TemplateView):
    template_name = 'gtd/_task.html'

    def get(self, request, *args, **kwargs):
        self.object = Task.objects.get(pk=kwargs['pk'])
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class ProjectDetails(TemplateView):
    template_name = 'gtd/_project.html'

    def get(self, request, *args, **kwargs):
        self.object = Project.objects.get(pk=kwargs['pk'])
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

gtd/tracker/templates/gtd/_project.html
<div class="well col-xs-12">
    <h2>{{ object.name }}</h2>
    <p>{{ object.description }}</p>
</div>

gtd/tracker/templates/gtd/_task.html
<div id="task-box-{{ object.id }}" class="task col-xs-12">
    <div class="well">
        <button class="close btn btn-danger btn-xs pull-right">
            <i class="fa fa-close" aria-hidden="true"></i>
        </button>
        <button class="more btn btn-danger btn-xs pull-right">
            <i class="fa fa-arrow-down" aria-hidden="true"></i>
        </button>
        <b>#{{ object.id }} {{ object }}</b>
        {% if object.link %}
            <small><a href="{{ object.link }}" target="_blank">{{ object.link }}</a></small>
        {% endif %}
        <div class="more" style="display: none;">
            <pre>{{ object.description }}</pre>
            <p>Status: {{ object.get_status_display }}</p>
        </div>
    </div>
</div>

gtd/tracker/templates/gtd/base.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title_text %}GTD{% endblock title_text %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/gtd.css' %}" />
{% endblock %}

{% block extra_js %}
{% endblock %}

gtd/tracker/templates/gtd/dashboard.html
{% extends "gtd/base.html" %}

{% load crispy_forms_tags %}
{% load staticfiles %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/gtd/dashboard.css' %}" />
{% endblock %}

{% block content %}
<div id="dashboard">
    <div class="row">
    <div class="col-xs-3">
        <h3><a href="{% url 'admin:gtd_projectcategory_changelist' %}" target="_blank">Kategorie</a>
            <a href="{% url 'admin:gtd_projectcategory_add' %}" target="_blank" class="pull-right btn btn-default btn-xs">
                <span class="fa fa-plus"></span>
            </a>
        </h3>
        <ul>
        {% for category in categories %}
            <li>
                <a href="#" class="category" data-id="{{ category.id }}" id="category-{{ category.id }}">{{ category }}</a>
                <a href="{% url 'admin:gtd_projectcategory_change' category.id %}" target="_blank" class="">
                    <span class="fa fa-edit"></span>
                </a>
            </li>
        {% endfor %}
        </ul>
    </div>
    <div class="col-xs-3">
        <h3><a href="{% url 'admin:gtd_projectcategory_changelist' %}" target="_blank">Podkategorie</a></h3>
        {% for category in categories %}
            <div class="subcategories" id="subcategories-{{ category.id }}">
                <ul>
                {% for subcategory in category.subcategories %}
                    <li>
                        <a href="#" class="subcategory" data-id="{{ subcategory.id }}" id="category-{{ subcategory.id }}">{{ subcategory.name }}</a>
                        <a href="{% url 'admin:gtd_projectcategory_change' subcategory.id %}" target="_blank" class="">
                            <span class="fa fa-edit"></span>
                        </a>
                    </li>
                {% endfor %}
                </ul>
            </div>
        {% endfor %}
    </div>

    <div class="col-xs-3">
        <h3><a href="{% url 'admin:gtd_project_changelist' %}" target="_blank">Projekty</a>
            <a href="{% url 'admin:gtd_project_add' %}" target="_blank" class="pull-right btn btn-default btn-xs">
                <span class="fa fa-plus"></span>
            </a>
        </h3>

        {% for category in categories %}
            <div class="projects" id="projects-{{ category.id }}">
                <ul>
                {% for project in category.projects.all %}
                    <li>
                        <a href="{% url 'gtd:project-details' project.id %}" class="project" data-id="{{ project.id }}" id="project-{{ project.id }}">{{ project }}</a>
                        <a href="{% url 'admin:gtd_project_change' project.id %}" target="_blank" class="">
                            <span class="fa fa-edit"></span>
                        </a>
                    </li>
                {% endfor %}
                </ul>
            </div>
            {% for subcategory in category.subcategories %}
                <div class="projects" id="projects-{{ subcategory.id }}">
                    <ul>
                        {% for project in subcategory.projects.all %}
                            <li>
                                <a href="{% url 'gtd:project-details' project.id %}" class="project" data-id="{{ project.id }}" id="project-{{ project.id }}">{{ project }}</a>
                                <a href="{% url 'admin:gtd_project_change' project.id %}" target="_blank" class="">
                                    <span class="fa fa-edit"></span>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
        {% endfor %}
    </div>

    <div class="col-xs-3">
        <h3><a href="{% url 'admin:gtd_task_changelist' %}" target="_blank">Zadania</a>
            <a href="{% url 'admin:gtd_task_add' %}" target="_blank" class="pull-right btn btn-default btn-xs">
                <span class="fa fa-plus"></span>
            </a>
        </h3>
        {% for category in categories %}
            {% for project in category.projects.all %}
                <div class="tasks" id="tasks-{{ project.id }}">
                    <ul>
                    {% for task in project.tasks.all %}
                        <li>
                            <a href="#" class="task-button" data-id="{{ task.id}}" id="task-button-{{ task.id }}"
                            data-url="{% url 'gtd:task-details' task.id %}">{{ task }}</a>
                            <a href="{% url 'admin:gtd_task_change' task.id %}" target="_blank" class="">
                                <span class="fa fa-edit"></span>
                            </a>
                        </li>
                    {% endfor %}
                    </ul>
                </div>
            {% endfor %}
            {% for subcategory in category.subcategories %}
                {% for project in subcategory.projects.all %}
                    <div class="tasks" id="tasks-{{ project.id }}">
                        <ul>
                        {% for task in project.tasks.all %}
                            <li>
                                <a href="#" class="task-button" data-id="{{ task.id}}" id="task-button-{{ task.id }}"
                                data-url="{% url 'gtd:task-details' task.id %}">{{ task }}</a>
                                <a href="{% url 'admin:gtd_task_change' task.id %}" target="_blank" class="">
                                    <span class="fa fa-edit"></span>
                                </a>
                            </li>
                        {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
            {% endfor %}
        {% endfor %}
    </div>
        </div>

    <div class="row" id="project-details">

    </div>

    <div class="row" id="tasks">

    </div>


</div>
{% endblock %}

{% block extra_js %}
    {{ block.super }}
    <script type="text/javascript">

        function setup_task_box(id) {
            var $box = $("#task-box-" + id);
            $box.find('.close').bind('click', function(){
                $box.remove();
                $('#task-button-' + id).removeClass('active');
            });
            $box.find('button.more').bind('click', function(){
                $box.find('div.more').toggle();
            });
        }

        function load_project_details(url) {
            $.ajax({
                url: url,
                type: 'get',
                success: function (response) {
                    $("#project-details").html(response);
                }
            });
        }

        $(function(){
            $('a.category').bind('click', function (){
                var id = $(this).data('id');
                $('a.category').removeClass('active');
                $('a.subcategory').removeClass('active');
                $('a.project').removeClass('active');
                $('.projects').hide();
                $('.subcategories').hide();
                $('.tasks').hide();
                $('#subcategories-' + id).show();
                $('#projects-' + id).show();
                $(this).addClass('active');
            });
            $('a.subcategory').bind('click', function (){
                var id = $(this).data('id');
                $('a.subcategory').removeClass('active');
                $('a.project').removeClass('active');
                $('.projects').hide();
                $('#projects-' + id).show();
                $(this).addClass('active');
            });
            $('a.project').bind('click', function (){
                $('a.project').removeClass('active');
                //$('a.task-button').removeClass('active');
                var id = $(this).data('id');
                $('.tasks').hide();
                $('#tasks-' + id).show();
                $(this).addClass('active');
                $("#tasks").html('');
                load_project_details($(this).attr('href'));
                return false;
            });

            $('a.task-button').bind('click', function (){
                if (!$(this).hasClass('active')) {
                    $(this).addClass('active');
                    var id = $(this).data('id');
                    var url = $(this).data('url');
                    $.ajax({
                        url: url,
                        type: 'get',
                        success: function (response) {
                            $("#tasks").append(response);
                            setup_task_box(id);
                        }
                    });
                }
            });
        });
    </script>
{% endblock %}